radius = input("Enter the radius of a circle")
radius = float(radius)
diameter = 2 * radius
circumference = 2 * 3.14 * radius
area = 3.14 * radius**2
print("circle radius =", radius)
print("diameter =", diameter)
print("circumference =",circumference)
print("area =",area)
